name: my_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_smart_dialog: ^4.9.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  provider: ^5.0.0
  dio: ^4.0.0
  flutter_lints: ^1.0.0
  firebase_core: ^2.12.0
  firebase_core_dart: ^1.0.1
  firebase_auth: ^4.6.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  fonts:
    - family: supermarket
      fonts:
        - asset: assets/fonts/supermarket.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand.ttf

  assets:
    - assets/images/
    - assets/